#!/usr/bin/env bash
# Transfer a file from client to server
# Check if the correct number of parameters is provided
if [ "$#" -lt 4 ];
then
	echo "Usage: $O PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Transfer the file using scp with strict host key checking is disabled
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/

# Check if the transfer is successful
if [ "$#" -eq 0 ]; then
	echo "File successfully transferred to $USERNAME@$SERVER_IP:~/"
else
	echo "Error transferring file."
fi
