#!/usr/bin/env bash
# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a simple HTML page with the string "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Start nginx service
service nginx start
# Restart nginx service
# /etc/init.d/nginx restart
