#!/usr/bin/env bash
# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a simple HTML page with the string "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Configure nginx to listen on port 80 and serve the HTML page
echo "server {
      listen 80;
      server_name localhost;

      location / {
           root /var/www/html;
	   index index.html;
      }
}" > /etc/nginx/sites-available/default
# Start nginx service
service nginx start
# Restart nginx service
# /etc/init.d/nginx restart
# Verify nginx is running
if [ "$(ps aux | grep nginx | grep -v grep)" ]; then
	echo "Execution successfull"
else
	echo "Execution not successful - output doesn't exist"
fi
