#!/usr/bin/env bash
# Update the package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a simple HTML page with the redirection message
echo '<html><head><meta http-equiv="refresh" content="0;url=https://www.youtube.com/watch?v=QH2-TGUlwu4" /></head></html>' | sudo tee /var/www/html/redirect_me/index.html > /dev/null

# Configure nginx for the redirection
echo "server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart nginx without using systemctl
# /etc/init.d/nginx restart
# Start nginx service
sudo service nginx start

