#!/usr/bin/env bash
# Create bash script that loops 10 times using while loop, if, elif and else statements
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
		else
		echo "Best School"
	fi
	((x++))
done
