#!/usr/bin/env bash
# Display numbers from 1 to 20 using while loop and case statements
x=1
while [ $x -le 20 ]
do
	echo "$x"
	case $x in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	((x++))
done
