#!/usr/bin/env bash
# Display the clock time 12 hours and 59 mins using while loop
hours=0
while [ $hours -le 12 ]
do
	echo "Hour: $hours"
	minutes=1
	while [ $minutes -lt 60 ]
	do
	echo "$minutes"
	((minutes++))
	done
	((hours++))
done
